import Head from "next/head";

import articles from "data/articles.json";
import { Article } from "components/Cards/Article";
import { ArticleType } from "types";
import { PublicLayout } from "components/Layouts";
import { Spacer } from "components/UI/Spacer";

interface IProps {
  articles: ArticleType[];
}

const Home = ({ articles }: IProps) => {
  return (
    <>
      <Head>
        <title>t.D. | Welcome</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <PublicLayout>
        <h1 style={{ textAlign: "center" }}>Stories</h1>
        <Spacer height="16px" />
        {articles.map((article) => {
          const props = {
            description: article.description,
            image: article.image,
            link: "/stories/" + article.slugname,
            subtitle: article.category,
            title: article.title,
          };
          return <Article key={article.id} {...props} />;
        })}
        <Spacer height="48px" />
      </PublicLayout>
    </>
  );
};

export const getStaticProps = async () => {
  return { props: { articles } };
};

export default Home;
